{{- if and (not .Values.config.devMode) (not .Values.config.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cozytempl.secretName" . }}
  labels:
    {{- include "cozytempl.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-client-secret: {{ required "config.oidc.clientSecret is required when devMode=false and no existingSecret is set" .Values.config.oidc.clientSecret | quote }}
  session-secret: {{ required "config.oidc.sessionSecret is required when devMode=false and no existingSecret is set" .Values.config.oidc.sessionSecret | quote }}
{{- end }}
