// Package authpage holds templ templates used by the auth package
// itself (e.g. the BYOK kubeconfig upload form). It lives here to
// avoid the import cycle that importing internal/view/partial would
// create (partial → k8s → auth → authpage).
package authpage

import (
	"context"

	"github.com/lexfrei/cozytempl/internal/i18n"
)

// tc is the package-local context-aware translation helper for
// authpage templates. It mirrors partial.Tc but lives here to avoid
// the import cycle that would result from importing internal/view/partial
// (which transitively depends on internal/auth via internal/k8s).
// Called by kubeconfig_upload_templ.go (generated by templ).
func tc(ctx context.Context, messageID string) string {
	loc := i18n.FromContext(ctx)
	if loc == nil {
		return "[" + messageID + "]"
	}

	return loc.T(messageID)
}
